---
- name: Install requirements
  apt:
    name: "{{item}}"
  with_items:
    - unzip
    - nagios-plugins
  become: yes
  become_user: root
  become_method: sudo

- name: install pip requirements
  pip:
    name: python-consul
  become: yes
  become_user: root
  become_method: sudo

- name: Get consul
  get_url:
    url: "https://releases.hashicorp.com/consul/{{consul_version}}/consul_{{consul_version}}_linux_amd64.zip"
    dest: "/usr/local/bin/consul_{{consul_version}}_linux_amd64.zip"
  become: yes
  become_user: root
  become_method: sudo

- name: Unzip consul
  command: "unzip /usr/local/bin/consul_{{consul_version}}_linux_amd64.zip"
  args:
    creates: "/usr/local/bin/consul"
    chdir: /usr/local/bin/
  become: yes
  become_user: root
  become_method: sudo

- name: make sure consul config directory exists
  file: path=/etc/consul.d state=directory
  become: yes
  become_user: root
  become_method: sudo

#- name: upload upstart script
#  template:
#    src: upstart.conf
#    dest: /etc/init/consul.conf
#  become: yes
#  become_user: root
#  become_method: sudo
#  notify: restart consul

- name: upload systemd script
  template:
    src: consul.service
    dest: /etc/systemd/system
  become: yes
  become_user: root
  become_method: sudo
  notify: restart consul

- name: Make sure consul is started
  service:
    name: consul
    state: started
    enabled: yes
  become: yes
  become_user: root
  become_method: sudo
