- hosts: 
  - all
  vars:
    - initial_cluster_size: 3
  pre_tasks:
    - name: Install ansible requirements
      pip:
        name: "docker-py"
        state: present
      tags:
        - swarm
  roles:
    - ubuntubase
    - docker
    - name: consul
      tags: 
        - consul

- hosts:
   - manager
   - replica
  tasks:

    #$ docker run -d -p 4000:4000 swarm manage -H :4000 --replication --advertise 172.30.0.161:4000 consul://172.30.0.161:8500
    - name: Run docker manager
      docker:
        name: swarm
        image: swarm
        command: "manage -H :4000 --replication --advertise {{private_ip}}:4000 consul://{{private_ip}}:8500"
        state: started
        ports:
          - "4000:4000"
        expose: 
          - 4000
      tags:
        - swarm

#- hosts:
#   - replica
#  tasks:
    #$ docker run -d swarm manage -H :4000 --replication --advertise <manager1_ip>:4000 consul://172.30.0.161:8500
#    - name: Run consul replica
#      docker:
#        name: swarm
#        image: swarm
#        command: "manage -H :4000 --replication --advertise {{private_ip}}:4000 consul://{{private_ip}}:8500"
#        state: started
#      tags:
#        - swarm

- hosts:
   - node
  tasks:
    #$ docker run -d swarm join --advertise=172.30.0.69:2375 consul://172.30.0.161:8500        
    - name: Run docker nodes
      docker:
        name: swarm
        image: swarm
        command: "join --advertise {{private_ip}}:4000 consul://{{private_ip}}:8500"
        state: started
      tags:
        - swarm






