---
# handlers file for base
- name: restart dnsmasq
  service: name=dnsmasq state=restarted enabled=yes
  become: yes
  become_user: root
  become_method: sudo
  
- name: restart resolvconf
  service: name=resolvconf state=restarted enabled=yes
  become: yes
  become_user: root
  become_method: sudo