---
- name: Update apt
  apt:
    update_cache: yes
  become: yes
  become_user: root
  become_method: sudo

- name: Install requirements
  apt:
    name: "{{item}}"
  with_items:
    - apt-transport-https
    - ca-certificates
  become: yes
  become_user: root
  become_method: sudo

- name: Add docker repo key
  apt_key:
    keyserver: "hkp://p80.pool.sks-keyservers.net:80"
    id: "58118E89F3A912897C070ADBF76221572C52609D"
    state: present
  become: yes
  become_user: root
  become_method: sudo

- name: Add docker repo
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo ubuntu-trusty main'
    state: present
  become: yes
  become_user: root
  become_method: sudo

- name: Update apt again
  apt:
    update_cache: yes
  become: yes
  become_user: root
  become_method: sudo

- name: Get the uname
  command: "uname -r"
  register: uname

#- name: install linux image extra
#  apt:
#    name: "linux-image-extra-{{uname.stdout}}"
#    state: present
#  become: yes
#  become_user: root
#  become_method: sudo

#- name: Install apparmor
#  apt:
#    name: apparmor
#    state: present
#  become: yes
#  become_user: root
#  become_method: sudo

- name: "Install docker engine!"
  apt:
    name: docker-engine
    state: present
  become: yes
  become_user: root
  become_method: sudo

- name: Make sure the docker directory exists
  file: path=/etc/docker state=directory
  become: yes
  become_user: root
  become_method: sudo

- name: Move the docker config files into place
  template:
    src: "{{ item }}"
    dest: /etc/docker/{{ item }}
  with_items:
    - daemon
    - networking
    - security
  become: yes
  become_user: root
  become_method: sudo

- name: Make sure cert directory exists
  file: path=/etc/docker/certs.d state=directory
  become: yes
  become_user: root
  become_method: sudo
  tags:
    - certs

- name: Install TLS certs
  copy: src=ca/{{item}} dest=/etc/docker/certs.d/{{item}}
  become: yes
  become_user: root
  become_method: sudo
  with_items:
    - "ca.pem"
    - "{{ node_hostname }}-cert.pem"
    - "{{ node_hostname }}-priv-key.pem"
  tags:
    - certs

- name: Create the systemd drop-in directory
  file: path=/etc/systemd/system/docker.service.d state=directory
  become: yes
  become_user: root
  become_method: sudo

- name: Add systemd drop-in
  template:
    src: docker.conf
    dest: /etc/systemd/system/docker.service.d/docker.conf
  become: yes
  become_user: root
  become_method: sudo
  notify:
    - reload systemd
    - restart docker

- name: Add docker group
  group:
    name: docker
    state: present

- name: Add mark to docker group
  user:
    name: mark
    group: docker
  become: yes
  become_user: root
  become_method: sudo

- name: Get uname -s
  command: "uname -s"
  register: unames
  tags:
    - with_compose

- name: Get uname -m
  command: "uname -m"
  register: unamem
  tags:
    - with_compose

- name: install compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.6.0/docker-compose-{{unames.stdout}}-{{unamem.stdout}}"
    dest: "/usr/local/bin/docker-compose"
  become: yes
  become_user: root
  become_method: sudo
  tags:
    - with_compose

- name: Add execution rights to file
  file:
    path: /usr/local/bin/docker-compose
    state: file
    mode: a+x
    group: docker
  become: yes
  become_user: root
  become_method: sudo
  tags:
    - with_compose
